triggers:
- envs: []
  last_enabled_at: 2024-03-28 05:27:46.479759
  name: tr1
  pipeline_uuid: github_daily_load
  schedule_interval: '@once'
  schedule_type: time
  settings:
    skip_if_previous_running: true
  sla: null
  start_time: 2024-03-28 05:22:00
  status: active
  variables:
    p_cluster_name: dpc-zoomcamp
    p_flag_stop_cluster: N
    p_gcs_bucket_name: de-zoomcamp-shamdzmi-bucket
    p_gcs_raw_path: data/raw/
    p_gcs_stage_path: data/stage/
    p_load_date: ''
    p_project_id: de-zoomcamp-shamdzmi
    p_pyspark_file: gs://de-zoomcamp-shamdzmi-bucket/Code/githunb_transform_raw_stage.py
    p_region: europe-west1
